### ISSUE TITLE
eval_demo.py fail - pytorch3d old ndc conventions

### ISSUE THREAD

**Issue by orweiser-code** [facebookresearch/co3d#21]
hey,
I am working with python 3.7, pytorch 1.9.1, pytorch3d 0.6.0 (which is the latest) but demo still fails with the exception

> Traceback (most recent call last):
  File "/media/data1/orweiser/anaconda3/envs/co3d/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/data1/orweiser/anaconda3/envs/co3d/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/orweiser/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/orweiser/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/orweiser/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/media/data1/orweiser/anaconda3/envs/co3d/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/media/data1/orweiser/anaconda3/envs/co3d/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/media/data1/orweiser/anaconda3/envs/co3d/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/orweiser/code/co3d/eval_demo.py", line 209, in <module>
    main()
  File "/home/orweiser/code/co3d/eval_demo.py", line 56, in main
    category, task=task, single_sequence_id=single_sequence_id
  File "/home/orweiser/code/co3d/eval_demo.py", line 110, in evaluate_dbir_for_category
    test_restrict_sequence_id=single_sequence_id,
  File "/home/orweiser/code/co3d/dataset/dataset_zoo.py", line 182, in dataset_zoo
    datasets[dataset] = Co3dDataset(**params)
  File "<string>", line 30, in __init__
  File "/home/orweiser/code/co3d/dataset/co3d_dataset.py", line 289, in __post_init__
    assert_pytorch3d_has_new_ndc_convention()
  File "/home/orweiser/code/co3d/tools/camera_utils.py", line 212, in assert_pytorch3d_has_new_ndc_convention
    "This codebase uses the new Pytorch3D NDC convention."

**Comment by shapovalov** [comment]
Hello. Your pytorch3d should be updated to include this commit:
https://github.com/facebookresearch/pytorch3d/commit/cac6cb1b7813a4f09a05e0ade43c63292bb08b79
Please either install pytorch3d-nightly:
`conda install pytorch3d -c pytorch3d-nightly`

or check out `master` branch and install as editable.

Sorry for this disruption but that is an urgent bug fix that can affect rendering results, and we did not want to wait for pytorch3d release.

**Comment by orweiser-code** [comment]
yes that did the trick... thanks
